#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-klaR
Version  : 1.7.3
Release  : 60
URL      : https://cran.r-project.org/src/contrib/klaR_1.7-3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/klaR_1.7-3.tar.gz
Summary  : Classification and Visualization
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-combinat
Requires: R-questionr
BuildRequires : R-combinat
BuildRequires : R-questionr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
e.g. regularized discriminant analysis, sknn() kernel-density naive Bayes, 
     an interface to 'svmlight' and stepclass() wrapper variable selection 
     for supervised classification, partimat() visualization of classification rules 
         and shardsplot() of cluster results as well as kmodes() clustering for categorical data, 
     corclust() variable clustering, variable extraction from different variable clustering models 
         and weight of evidence preprocessing.

%prep
%setup -q -n klaR
pushd ..
cp -a klaR buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702945538

%install
export SOURCE_DATE_EPOCH=1702945538
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/klaR/CITATION
/usr/lib64/R/library/klaR/DESCRIPTION
/usr/lib64/R/library/klaR/INDEX
/usr/lib64/R/library/klaR/Meta/Rd.rds
/usr/lib64/R/library/klaR/Meta/data.rds
/usr/lib64/R/library/klaR/Meta/features.rds
/usr/lib64/R/library/klaR/Meta/hsearch.rds
/usr/lib64/R/library/klaR/Meta/links.rds
/usr/lib64/R/library/klaR/Meta/nsInfo.rds
/usr/lib64/R/library/klaR/Meta/package.rds
/usr/lib64/R/library/klaR/NAMESPACE
/usr/lib64/R/library/klaR/NEWS
/usr/lib64/R/library/klaR/R/klaR
/usr/lib64/R/library/klaR/R/klaR.rdb
/usr/lib64/R/library/klaR/R/klaR.rdx
/usr/lib64/R/library/klaR/data/B3.RData
/usr/lib64/R/library/klaR/data/GermanCredit.RData
/usr/lib64/R/library/klaR/data/countries.RData
/usr/lib64/R/library/klaR/help/AnIndex
/usr/lib64/R/library/klaR/help/aliases.rds
/usr/lib64/R/library/klaR/help/klaR.rdb
/usr/lib64/R/library/klaR/help/klaR.rdx
/usr/lib64/R/library/klaR/help/paths.rds
/usr/lib64/R/library/klaR/html/00Index.html
/usr/lib64/R/library/klaR/html/R.css
/usr/lib64/R/library/klaR/tests/EDAM.R
/usr/lib64/R/library/klaR/tests/EDAM.Rout.save
/usr/lib64/R/library/klaR/tests/EDAM.ps.save
/usr/lib64/R/library/klaR/tests/testklaR.ps.save
/usr/lib64/R/library/klaR/tests/testsklaR.R
/usr/lib64/R/library/klaR/tests/testsklaR.Rout.save
